---
# 1. DEPLOYMENT
apiVersion: apps/v1
kind: Deployment
metadata:
  name: projeto-contas
  namespace: projeto-contas  # <--- MUDOU AQUI
  labels:
    app: projeto-contas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: projeto-contas
  template:
    metadata:
      labels:
        app: projeto-contas
    spec:
      containers:
      - name: python-app
        # O Jenkins vai atualizar a tag automaticamente
        image: dockerhub-pedro/projeto-contas:latest
        ports:
        - containerPort: 5000
        
        env:
        # --- CONEXÃO COM O BANCO (Cross-Namespace) ---
        - name: MYSQL_HOST
          # Aponta para o serviço no namespace 'database'
          value: "mysql.database.svc.cluster.local"
        
        - name: MYSQL_USER
          value: "quarkus-user"
          
        - name: MYSQL_DATABASE
          value: "kafkadb"
          
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-creds    # Lê o secret que criamos no passo 1
              key: user-password
              
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"

---
# 2. SERVICE
apiVersion: v1
kind: Service
metadata:
  name: projeto-contas-svc
  namespace: projeto-contas  # <--- MUDOU AQUI
spec:
  selector:
    app: projeto-contas
  ports:
  - port: 80
    targetPort: 5000

---
# 3. INGRESSROUTE (Traefik)
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: projeto-contas-ingress
  namespace: projeto-contas  # <--- MUDOU AQUI
spec:
  entryPoints:
    - web
  routes:
  # Rota ajustada. Se quiser mudar o subdomínio, fique à vontade.
  - match: Host(`contas.local.174.138.111.100.nip.io`)
    kind: Rule
    services:
    - name: projeto-contas-svc
      port: 80