---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: projeto-contas
  namespace: projeto-contas
  labels:
    app: projeto-contas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: projeto-contas
  template:
    metadata:
      labels:
        app: projeto-contas
    spec:
      containers:
      - name: python-app
        image: pedropvp/projeto-contas:13
        ports:
        - containerPort: 5000
        env:
        - name: MYSQL_HOST
          value: "mysql.database.svc.cluster.local"
        - name: MYSQL_USER
          value: "quarkus-user"
        - name: MYSQL_DATABASE
          value: "kafkadb"
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-creds
              key: user-password
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: projeto-contas-svc
  namespace: projeto-contas
spec:
  selector:
    app: projeto-contas
  ports:
  - port: 80
    targetPort: 5000
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: projeto-contas-ingress
  namespace: projeto-contas
spec:
  entryPoints:
    - web
    - websecure
  routes:
  - match: Host(`contas.local.174.138.111.100.nip.io`)
    kind: Rule
    services:
    - name: projeto-contas-svc
      port: 80